### ISSUE TITLE
Issue when having ContentControl as Content in ContentControl

### ISSUE THREAD

**Issue by amerkoleci** [grokys/Perspex#47]
Maybe the title can be missleading but there is an issue with template create when having something like this:

```
var window = new Window()
{
  Content = new ContentControl
  {
      Content = new TreeView
      {
           Items = treeData
      }
  }
}
```

**Comment by grokys** [comment]
Could you tell me what the issue is? If I paste your code snippet into the Perspex TestApplication, it runs as expected.

**Comment by amerkoleci** [comment]
I don't see the TreeView, if I remove the ContentControl and set it directly to Window Content it works.

**Comment by grokys** [comment]
Hmm I'm not seeing that, but I did have some unpushed changes here locally. Could you try pulling from git and trying again.

This is what I did to test:

- Comment out the whole of the `Window window = new Window` declaration in TestApplication and replace it with your code above.
- Comment out the block below `var renderer = ((IRenderRoot)window).Renderer;`
- Run the program.

I get this:

![image](https://cloud.githubusercontent.com/assets/1775141/7472174/e82e8140-f32f-11e4-98f8-498053c084d9.png)

**Comment by amerkoleci** [comment]
Found the issue, I had custom control deriving from ContentControl as for IStyleable.StyleKey it was not founding the
style key for my custom control, deriving from UserControl worked, would be fine to find style from base class if not found
from current one.

**Comment by grokys** [comment]
Ok, great - the problem with automatically using the style for a base class instead of the most derived class is that at the point of style binding it's not known whether a style will be found or not. There may be a better way around this, but at the moment indeed it's recommended to derive from `UserControl` or set the style key in your derived class.

Thanks for working through the problem, I know it's not easy when the project is in this early stage!
